language: node_js
node_js:
  - '13'
services:
  - docker
install:
  - npm ci
script:
  - npm run test-coverage
before_deploy:
  - git remote add origin \"https://${GITHUB_TOKEN}@github.com/undefinedhuman/sts-blog.git\" > /dev/null 2>&1
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*" 1>/dev/null
  - git fetch origin -q
deploy:
    provider: script
    script: bash deploy.sh
    on:
      branch: master
