language: node_js
node_js:
  - '13'
services:
  - docker
install:
  - 'npm ci'
script:
  - npm run coveralls
deploy:
    provider: script
    script: bash scripts/deploy.sh
    on:
      branch: master
