language: node_js
node_js:
  - '13'
services:
  - docker
install:
  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*" 1>/dev/null
  - git fetch origin -q
  - 'npm ci'
script:
  - npm run test-coverage
deploy:
    provider: script
    script: bash deploy.sh
    on:
      branch: master
